name: CI Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  CI-Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
  
    - name: Checkout this Repo
      uses: actions/checkout@v4
      with:
        path: antares-results

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        cd antares-results
        flake8 amplitudes/ --count --max-line-length=190 --statistics --verbose
